"""Bias guards applied at score time.

Self-enhancement (per SPEC §6.3): an LLM judge tends to prefer outputs
generated by its own model family. We compare the judge model's
provider against the generator's provider (lifted from record input or
trace gen_ai_system attributes). If they match, we set the
`self_enhancement_warning` flag on the score row so the UI can badge
the score and downstream calibration can drop it from κ math.
"""

from __future__ import annotations

# Map litellm-style "provider/model" prefixes + raw provider names to a
# coarse "family" we treat as identical for self-enhancement purposes.
_FAMILY: dict[str, str] = {
    "anthropic": "anthropic",
    "claude": "anthropic",
    "openai": "openai",
    "azure": "openai",
    "gpt": "openai",
    "google": "google",
    "vertex_ai": "google",
    "gemini": "google",
    "mistral": "mistral",
    "meta": "meta",
    "llama": "meta",
}


def model_family(identifier: str) -> str:
    """Reduce a model id or provider string to a coarse family.

    Accepts litellm "provider/model" strings, bare provider names, or
    partial matches (e.g. 'claude-3' → 'anthropic'). Returns 'unknown'
    when nothing matches; the guard treats unknown as non-matching.
    """
    if not identifier:
        return "unknown"
    s = identifier.lower()
    if "/" in s:
        s = s.split("/", 1)[0]
    for needle, fam in _FAMILY.items():
        if needle in s:
            return fam
    return "unknown"


def self_enhancement(judge_model: str, generator: str) -> bool:
    """True when judge + generator share a coarse family."""
    j = model_family(judge_model)
    g = model_family(generator)
    if j == "unknown" or g == "unknown":
        return False
    return j == g
